const questions = [
	{
		'id':1,
		'title':'次のうち、摂食、体温、情動の調節に関わっている中枢神経の部位として、正しい物を一つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">１ 橋<br><br><input type="checkbox" name="checks" value="2" class="checks">2 中枢<br><br><input type="checkbox" name="checks" value="3" class="checks">3 小脳<br><br><input type="checkbox" name="checks" value="4" class="checks">4 視床<br><br><input type="checkbox" name="checks" value="5" class="checks">5 視床下部',
		'answer':'5',
	},
	{
		'id':2,
		'title':'Aさん(68歳 男性)は脳梗塞の既往がある。日常生活は支障がなく、自立していた。慢性腎不全の治療で入院中、３日前から38℃の発熱があり昨夜に解熱鎮静剤を服用したところ、出勤すると言って深夜に着替えて出掛けようとした。今朝は傾眠状態である。<br><br>次のうち、この患者に疑われる疾患又は病態として，適切なものを1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">１ 急性ストレス反応（急性ストレス障害）<br><br><input type="checkbox" name="checks" value="2" class="checks"> 2 身体症状症（身体表現性障害）<br><br><input type="checkbox" name="checks" value="3" class="checks">3 統合失調症<br><br><input type="checkbox" name="checks" value="4" class="checks">4 せん妄<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アルツハイマー型認知症',
		'answer':'4',
	},
	{
		'id':3,
		'title':'次のうち，境界性パーソナリティ障害の特徴として，適切なものを1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 良心の呵責の欠如<br><br><input type="checkbox" name="checks" value="2" class="checks"> 2 自分が重要であるという誇大な感覚<br><br><input type="checkbox" name="checks" value="3" class="checks">3 他人の感情への冷淡で無関心な行動<br><br><input type="checkbox" name="checks" value="4" class="checks">4 疑い深く，人に恨みを持ち続ける傾向<br><br><input type="checkbox" name="checks" value="5" class="checks">5 見捨てられることを避けようとするなりふり構わない努力',
		'answer':'5',
	},
	{
		'id':4,
		'title':'次のうち、うつ病でみられることがある症状として、適切なものを2つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 過眠<br><br><input type="checkbox" name="checks" value="2" class="checks">2 せん妄<br><br><input type="checkbox" name="checks" value="3" class="checks">3 誇大妄想<br><br><input type="checkbox" name="checks" value="4" class="checks">4 食欲抗進<br><br><input type="checkbox" name="checks" value="5" class="checks">5 知能低下',
		'answer':'1,4',
	},
	{
		'id':5,
		'title':'次の記述のうち，注意欠如・多動症（ＡＤＨＤ）の不注意の症状として,正しいものを２つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 しゃべりすぎる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 日々の活動で忘れっぽい。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 自分の順番を待つことが困難である。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 課題や活動を順序立てることが困難である。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 不適切な状況で走り回ったり高い所へ登ったりする。',
		'answer':'2,4',
	},
	{
		'id':6,
		'title':'次の記述のうち，認知症患者に用いられるドネペジル塩酸塩について,正しいものを1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 効能は認知機能の回復である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 血管性認知症に適応がある。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 心疾患には特に注意が必要である。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 服薬を中止すると強い離脱症状を認める。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 神経伝達物質であるアセチルコリンの分解を促進する。',
		'answer':'3',
	},
	{
		'id':7,
		'title':'次のうち，森田療法で用いられる理論や技法として,正しいものを1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 転移<br><br><input type="checkbox" name="checks" value="2" class="checks">2 絶対臥褥<br><br><input type="checkbox" name="checks" value="3" class="checks">3 フラッディング<br><br><input type="checkbox" name="checks" value="4" class="checks">4 古典的条件づけ<br><br><input type="checkbox" name="checks" value="5" class="checks">5 カタルシス効果',
		'answer':'2',
	},
	{
		'id':8,
		'title':'次の記述のうち，精神科を主たる診療科名として標榜する診療所について、正しいものを2つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 在宅医療を提供できる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 開設者には精神保健指定医の資格が必須である。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 自立支援医療（精神通院医療）を利用できる。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 精神保健福祉士の勤務が必須である。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 「医療施設（静態・動態）調査」（厚生労働省）によると，2011 年（平成 23 年）以降，診療所数が著しく減少している。',
		'answer':'1,3',
	},
	{
		'id':9,
		'title':'次のうち，精神保健指定医の診察の結果，応急入院が妥当と考えられる患者として，適切なものを1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 自ら治療を求めて来院した不安障害の患者<br><br><input type="checkbox" name="checks" value="2" class="checks">2 妻が付き添って来院した振戦せん妄の患者<br><br><input type="checkbox" name="checks" value="3" class="checks">3 身元の全く分からない不穏で独語のある患者<br><br><input type="checkbox" name="checks" value="4" class="checks">4 家族に対して易怒的で，長男に連れてこられた前頭側頭型認知症の患者<br><br><input type="checkbox" name="checks" value="5" class="checks">5 幻覚・妄想が強く自傷他害のおそれのある統合失調症の患者',
		'answer':'3',
	},
	{
		'id':10,
		'title':'次の記述のうち，精神障害者の入院形態として，正しいものを１つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 任意入院では，48 時間に限り退院制限を行うことができる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 医療保護入院では，家族等の同意により本人を入院させることができる。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 措置入院は，家庭裁判所の権限による入院形態である。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 緊急措置入院は，夜間に限って行われる。<br><br><input type="checkbox" name="checks" value="5" class="checks">5「医療観察法」による鑑定入院は，都道府県知事の権限による入院である。',
		'answer':'2',
	},
	{
		'id':11,
		'title':'次の記述のうち，厚生労働省の「健康づくりのための睡眠指針 2014」に示されている内容として、正しいものを 2つ 選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 うつ病に伴う不眠症状では，睡眠による休養感の欠如が最も特徴的である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 成人してから加齢するにつれて夜間の睡眠時間が増加する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 蓄積された睡眠不足に伴う作業能率は「寝だめ」で十分回復する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 睡眠薬代わりの寝酒は睡眠を悪くする。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 眠くなくても，寝床に入る習慣をつける。',
		'answer':'1,4',
	},
	{
		'id':12,
		'title':'次のうち，予防精神医学の概念を提唱した人物として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 ソンダース（Saunders, C.）<br><br><input type="checkbox" name="checks" value="2" class="checks">2 カプラン（Caplan, G.）<b<input type="checkbox" name="checks" value="3" class="checks">r><br>3 呉秀三<<input type="checkbox" name="checks" value="4" class="checks">br><br>4 <input type="checkbox" name="checks" value="5" class="checks">ピアジェ（Piaget, J.）<br><br>5 フロイト（Freud, S.）',
		'answer':'2',
	},
	{
		'id':13,
		'title':'次のうち，「児童虐待防止法」に定められているものとして，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 児童相談所の設置<br><br><input type="checkbox" name="checks" value="2" class="checks">2 要保護児童対策地域協議会の設置<br><br><input type="checkbox" name="checks" value="3" class="checks">3 被措置児童等虐待に係る通告<br><br><input type="checkbox" name="checks" value="4" class="checks">4 家庭裁判所による保護者の接近禁止命令<br><br><input type="checkbox" name="checks" value="5" class="checks">5 児童虐待の定義',
		'answer':'5',
	},
	{
		'id':14,
		'title':'次のうち，性行不良で他の児童の教育に妨げがあると認められる児童がいた場合に，市町村の教育委員会がその保護者に対して，当該児童の出席停止を命ずることができると規定している法律として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 子ども・子育て支援法<br><br><input type="checkbox" name="checks" value="2" class="checks">2 学校保健安全法<br><br><input type="checkbox" name="checks" value="3" class="checks">3 教育基本法<br><br><input type="checkbox" name="checks" value="4" class="checks">4 学校教育法<br><br><input type="checkbox" name="checks" value="5" class="checks">5 社会教育法',
		'answer':'4',
	},
	{
		'id':15,
		'title':'次のうち，心身症患者の特徴を表す概念として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 アカシジア<br><br><input type="checkbox" name="checks" value="2" class="checks">2 アタッチメント<br><br><input type="checkbox" name="checks" value="3" class="checks">3 アドヒアランス<br><br><input type="checkbox" name="checks" value="4" class="checks">4 アイデンティティ<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アレキシサイミア',
		'answer':'5',
	},
	{
		'id':16,
		'title':'アルコール健康障害対策基本法に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 酒に酔っている者の行為を規制し，又は救護を要する酩めい酊てい者を保護する等の措置を講ずることによって，過度の飲酒の害悪を防止することを目的としている。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 重度アルコール依存症入院医療管理加算の施設基準を定めている。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 アルコール健康障害に関連して生じる飲酒運転，暴力，虐待，自殺等の問題をアルコール関連問題としている。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 都道府県及び市町村に対し，アルコール健康障害対策推進基本計画の策定義務を規定している。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アルコールの輸入，輸出，製造，譲渡に関する規定がある。',
		'answer':'3',
	},
	{
		'id':17,
		'title':'次のうち，自殺対策におけるポストベンションの活動として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 自殺で亡くなった中学生の同級生に対して実施される心のケア<br><br><input type="checkbox" name="checks" value="2" class="checks">2 自殺対策強化月間におけるインターネットを活用した支援窓口の広報<br><br><input type="checkbox" name="checks" value="3" class="checks">3 救命救急センターに搬送された自殺未遂者に対するフォローアップ支援<br><br><input type="checkbox" name="checks" value="4" class="checks">4 地域住民に対するうつ病予防のための講演会<br><br><input type="checkbox" name="checks" value="5" class="checks">5 希死念慮を有する者を対象とした電話による相談',
		'answer':'1',
	},
	{
		'id':18,
		'title':'次のうち，女性よりも男性に多く認められるメンタルヘルスの問題として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 うつ病<br><br><input type="checkbox" name="checks" value="2" class="checks">2 抜毛症<br><br><input type="checkbox" name="checks" value="3" class="checks">3 自閉スペクトラム症<br><br><input type="checkbox" name="checks" value="4" class="checks">4 転換性障害<br><br><input type="checkbox" name="checks" value="5" class="checks">5 選択性緘黙',
		'answer':'3',
	},
	{
		'id':19,
		'title':'次のうち，「精神保健福祉法」に規定されている精神保健福祉センターの業務として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 精神保健指定医の指定<br><br><input type="checkbox" name="checks" value="2" class="checks">2 精神保健審判員の任命<br><br><input type="checkbox" name="checks" value="3" class="checks">3 精神科病院入院患者の退院請求の審査<br><br><input type="checkbox" name="checks" value="4" class="checks">4 精神医療審査会の事務<br><br><input type="checkbox" name="checks" value="5" class="checks">5 自立支援医療（精神通院医療）の申請受付',
		'answer':'4',
	},
	{
		'id':20,
		'title':'ＷＨＯによるメンタルヘルスアクションプラン 2013－2020 に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 国際疾病分類（ＩＣＤ）の改訂を目標とした。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 アルマ・アタ宣言とも呼ばれている。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 「メンタルヘルスなしに健康なし」を原則としている。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 精神疾患を有する者の非自発的な入院をなくすことが目標に定められた。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 中低所得国における精神保健サービスの拡充を主たる目的としている。',
		'answer':'3',
	},
	{
		'id':21,
		'title':'次のうち，グリーンウッド（Greenwood, E.）が掲げたソーシャルワーク専門職の属性として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 個人的な責任を伴う，理論を携えた活動であること<br><br><input type="checkbox" name="checks" value="2" class="checks">2 地域社会の承認があること<br><br><input type="checkbox" name="checks" value="3" class="checks">3 専門職を養成するための教育システム及びその訓練課程があること<br><br><input type="checkbox" name="checks" value="4" class="checks">4 利他的な動機があること<br><br><input type="checkbox" name="checks" value="5" class="checks">5 構成員の大多数が加入している専門職能団体があること',
		'answer':'2',
	},
	{
		'id':22,
		'title':'次の記述のうち，精神保健福祉の理論や実践に影響を与えた人物の説明として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 ジョーンズ（Jones, M.）は，病院の全環境を治療手段として用いる治療共同体の概念を提唱した。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ミニューチン（Minuchin, S.）は，集団や人間の相互依存性によるグループダイナミクスに着目した。<b<input type="checkbox" name="checks" value="3" class="checks">r><br>3 <input type="checkbox" name="checks" value="4" class="checks">ロジャーズ（Rogers, C.）は，様々な心理療法やカウンセリング理論の基本となっている面接技法を統合したマイクロカウンセリングを開発した。<br<input type="checkbox" name="checks" value="5" class="checks">><br>4 レヴィン（Lewin, K.）は，システム理論に基づいた構造的家族療法を展開し，家族成員間の境界に着目した。<br><br>5 アイビイ（Ivey, A.）は，非指示的アプローチである来談者中心療法（クライエント中心療法）を確立した。',
		'answer':'1',
	},
	{
		'id':23,
		'title':'事例を読んで，この時点で，サービス管理責任者であるＢ精神保健福祉士がＣさんに行うべき対応として，適切なものを 1 つ選びなさい。<br><br>〔事　例〕<br><br>就労移行支援事業所を利用しているＣさん（47 歳，男性）は，企業への就職を目標としている。支援を受けながら就職活動を続けているが，採用面接を受けてもなかなか決まらないでいる。最近では，イライラを募らせ物に当たったり，反対に塞ぎ込んだりする様子が見られていた。昨日，Ｃさんは感情を抑えることができず，若い職員に対して，「なぜ，他の人には良い職場を紹介するんだ」「どうせ俺は働けないと馬鹿にしているんだろう」「お前は素人か」と語気を強めた。そこでＢ精神保健福祉士は，今後のことについてＣさんと話合いをすることにした。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 就職に結び付かない現状を受け止められるよう，つらさをくみとる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 若い職員であっても，十分な知識や技術を持っていることを説明する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 これからはＣさんと同年代の職員が，常に担当することを提案する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 求職活動を一旦中断し，趣味の時間を増やすことを勧める。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 感情を抑えることができなければ，利用中止になることを伝える。',
		'answer':'1',
	},
	{
		'id':24,
		'title':'次の記述のうち，精神保健福祉士が行う自立支援として，適切なものを 1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 サービス担当者会議では，クライエントの混乱を避けるため，必要なサービスの利用に関する説明は最小限で行う。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 福祉制度の活用を希望しているクライエントには，その理由について聞くとともに，申請の手続の説明を行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 地域で生活をしているクライエントには，フォーマルネットワークよりインフォーマルネットワークを優先した支援を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 非自発的入院となったクライエントには，任意入院に切り替わってから退院支援を行う。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 セルフヘルプグループの活動では，グループワークの技法を積極的に使用して，援助を行う。',
		'answer':'2',
	},
	{
		'id':25,
		'title':'福祉行政・関連行政機関に勤務する職員の主たる業務に関する次の記述のうち，正しいものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 児童福祉司は，子どもや保護者からの相談に応じ，家族関係の調整等を行う。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 障害者職業カウンセラーは，障害者の職場で支援計画に基づく直接支援を行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 知的障害者福祉司は，公共職業安定所（ハローワーク）に配置され，職業紹介を行うために必要な援助について明らかにする。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 保護観察官は，医療観察制度の対象者の精神保健観察を行う。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 精神保健福祉相談員は，精神保健及び精神障害者の福祉に関する相談に応じ，必要な指導を行う。',
		'answer':'1,5',
	},
	{
		'id':26,
		'title':'次の記述のうち，「障害者総合支援法」に基づくサービスを提供する者が行う業務として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 施設長（管理者）は，個別支援計画の策定や評価を行い，サービスの進捗状況を管理する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 生活相談員は，障害者からの相談対応，情報提供，連絡調整等の支援やサービス等利用計画の作成を行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 相談支援専門員は，入所施設に必置とされ，入退所における面接や利用者の相談援助を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 サービス管理責任者は，社会福祉施設における専任の管理者であり，運営管理を行う。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 居宅介護従業者は，地域で生活する障害者への訪問による介護を行う。',
		'answer':'5',
	},
	{
		'id':27,
		'title':'精神障害者の権利擁護に関する次の記述のうち，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 インフォームドコンセントとは，必要だと考えられる治療や検査の方法について，十分な説明をすることである。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 リーガルアドボカシーとは，障害者自らが，法的な面から権利を主張する活動のことである。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 援助の記録は，事実の経過や根拠を証明する資料として，権利擁護に貢献するものである。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 ピアアドボカシーとは，地域の中で障害者が当たり前の生活を営めるように，市民参画型の活動を展開することである。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 合理的配慮とは，障害者が他の者と平等に全ての人権や基本的自由を享有するための，必要かつ適当な変更や調整のことである。',
		'answer':'3,5',
	},
	{
		'id':28,
		'title':'ジェネラリスト・ソーシャルワークの成り立ちに影響を与えたモデルやアプローチに関する次の記述のうち，最も時期が古いものとして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 クライエントと地域社会が有する問題解決能力の強さを評価し，積極的に活用しようとするストレングスモデルが提唱された。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ソーシャルワークの共通基盤を確立した上で，そこから全体を特質づける枠組みを再構築するジェネラリストアプローチにより統合化が進んだ。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 エコロジカル・ソーシャルワークが台頭し，人と環境の相互作用に焦点を当てた生活モデルが提唱された。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 社会的に不利な状況に置かれた人の自己決定の能力や主張性を高め，主体的にその状況に働きかけ，改善するエンパワメントアプローチが台頭してきた。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 「状況の中の人」に焦点を当てて，クライエントの問題状況を捉える心理社会的アプローチが提唱された。',
		'answer':'5',
	},
	{
		'id':29,
		'title':'次の記述のうち，マルチディシプリナリ・モデルの説明として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 専門職はあらかじめ決められた役割をこなす<br><br><input type="checkbox" name="checks" value="2" class="checks">2 各職種の役割はおおむね固定的であるものの，一部流動することもある。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 多職種間で役割固定がなく，横断的な支援を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 各職種の専門性を基に活発に意見交換する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 専門職間に階層性がなく，相互作用性は大きい。',
		'answer':'1',
	},
	{
		'id':30,
		'title':'次の事例を読んで，問題 30 について答えなさい。<br><br>〔事　例〕<br><br>Ｄ精神保健福祉士は，処方薬への依存のためにＵ精神科病院の薬物依存症外来に通うＥさん（26 歳，女性）が減薬を目的に入院したことを契機に担当となった。主治医から話を聞いたり電子カルテの情報を確認したりしたＤ精神保健福祉士は，Ｅさんが，幼少期の実母による過酷な虐待や，思春期における性的被害の経験を有していることを把握した。そこで，薬物問題に加え，過去の逆境体験に対する理解や，その体験が現在に及ぼす影響をも視野に入れた支援が必要であると考えた。<br><br>（問題 30）<br>次のうち，この時点でＤ精神保健福祉士が意識したＥさんに対するアプローチとして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 フェミニストアプローチ<br><br><input type="checkbox" name="checks" value="2" class="checks">2 課題中心アプローチ<br><br><input type="checkbox" name="checks" value="3" class="checks">3 ナラティブアプローチ<br><br><input type="checkbox" name="checks" value="4" class="checks">4 トラウマインフォームドアプローチ<br><br><input type="checkbox" name="checks" value="5" class="checks">5 解決志向アプローチ',
		'answer':'4',
	},
	{
		'id':31,
		'title':'次の事例を読んで，問題 31 について答えなさい。<br><br>〔事　例〕<br><br>Ｄ精神保健福祉士は，処方薬への依存のためにＵ精神科病院の薬物依存症外来に通うＥさん（26 歳，女性）が減薬を目的に入院したことを契機に担当となった。主治医から話を聞いたり電子カルテの情報を確認したりしたＤ精神保健福祉士は，Ｅさんが，幼少期の実母による過酷な虐待や，思春期における性的被害の経験を有していることを把握した。そこで，薬物問題に加え，過去の逆境体験に対する理解や，その体験が現在に及ぼす影響をも視野に入れた支援が必要であると考えた。<br><br>（問題 31）<br>入院時のＥさんは挑発的態度を繰り返しており，病棟スタッフとの信頼関係を築けずにいた。Ｄ精神保健福祉士は，過去の体験に基づく強い人間不信や自己否定感が根底にあることを読み取り，温かく落ち着いた関わりを続けた。その結果，Ｅさんは，主治医とＤ精神保健福祉士には心を許すようになり，「死にたい」と苦しい胸の内を打ち明けるようにもなった。<br><br>次の記述のうち，Ｄ精神保健福祉士がこの時点において行った対応として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 Ｅさんには内緒で，両親に希死念慮があることを話した。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 つらくても死んだりしないという約束をＥさんから取りつけた。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 どんなときに死にたくなるかをＥさんに尋ねた。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 人の命がいかに尊いものかをＥさんに説明した。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 Ｅさんが正直に気持ちを話してくれたことへの感謝を伝えた。',
		'answer':'3',
	},
	{
		'id':32,
		'title':'次の事例を読んで，問題 32 について答えなさい。<br><br>〔事　例〕<br><br>Ｄ精神保健福祉士は，処方薬への依存のためにＵ精神科病院の薬物依存症外来に通うＥさん（26 歳，女性）が減薬を目的に入院したことを契機に担当となった。主治医から話を聞いたり電子カルテの情報を確認したりしたＤ精神保健福祉士は，Ｅさんが，幼少期の実母による過酷な虐待や，思春期における性的被害の経験を有していることを把握した。そこで，薬物問題に加え，過去の逆境体験に対する理解や，その体験が現在に及ぼす影響をも視野に入れた支援が必要であると考えた。<br><br>入院時のＥさんは挑発的態度を繰り返しており，病棟スタッフとの信頼関係を築けずにいた。Ｄ精神保健福祉士は，過去の体験に基づく強い人間不信や自己否定感が根底にあることを読み取り，温かく落ち着いた関わりを続けた。その結果，Ｅさんは，主治医とＤ精神保健福祉士には心を許すようになり，「死にたい」と苦しい胸の内を打ち明けるようにもなった。<br><br>（問題 32）<br>Ｅさんは，病棟内のプログラム参加には消極的で，ルール違反ばかり繰り返していた。スタッフに注意されると，暴言を吐いたり自殺をほのめかしたりするので，スタッフの間にはＥさんに対するネガティブな感情や不全感が蓄積され，いつしか病棟チーム全体が機能不全に陥りつつあった。そこで，Ｄ精神保健福祉士はケアカンファレンスでＥさんを取り上げることを提案した。その中で病状や治療方針を共有したり，スタッフがＥさんとの関わりの中で受けた傷つきや恐れの気持ちを表出できるよう働きかけたりした。また，相互の役割を確認し，日々の苦労をスタッフ間でねぎらい合えるようにした。その結果，病棟チームにあった刺々しい雰囲気が薄れ，Ｅさんの言動も徐々に落ち着きをみせるようになった。<br><br>次のうち，Ｄ精神保健福祉士がケアカンファレンスを通して病棟チームに果たした機能として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 管理的機能<br><br><input type="checkbox" name="checks" value="2" class="checks">2 メンテナンス機能<br><br><input type="checkbox" name="checks" value="3" class="checks">3 教育的機能<br><br><input type="checkbox" name="checks" value="4" class="checks">4 タスク機能<br><br><input type="checkbox" name="checks" value="5" class="checks">5 支持的機能',
		'answer':'2',
	},
	{
		'id':33,
		'title':'スーパービジョンに向け，自分の関わりを振り返った精神保健福祉士（34 歳，女性）の記録（事例）を読んで，問題 33 について答えなさい。<br><br>〔事　例〕<br><br>Ｆさん（32 歳，女性）は，私が勤務する精神科病院に 18 歳から統合失調症で入院していた。私が担当になったのはＦさんが 22 歳の春だった。入院中のＦさんは年配者と過ごすことが多かったため，ロールモデルにできる人がおらず自分の将来像を描けないでいた。そのため，同世代である私は会うたびに話しかけ，Ｆさんの将来について語ってもらった。このことに刺激を受けたＦさんは，次第に自分自身の存在を認め，退院を考えるようになった。<br><br>（問題 33）<br><br>次のうち，この時点で「私」がＦさんとの関わりの際に支援目標として意識したこととして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 セルフエスティームの向上<br><br><input type="checkbox" name="checks" value="2" class="checks">2 服薬を自己管理する能力の向上<br><br><input type="checkbox" name="checks" value="3" class="checks">3 ストレスに対処する技術の向上<br><br><input type="checkbox" name="checks" value="4" class="checks">4 社会生活技能の向上<br><br><input type="checkbox" name="checks" value="5" class="checks">5 権利を主張する能力の向上',
		'answer':'1',
	},
	{
		'id':34,
		'title':'スーパービジョンに向け，自分の関わりを振り返った精神保健福祉士（34 歳，女性）の記録（事例）を読んで，問題 34について答えなさい。<br><br>〔事　例〕<br><br>Ｆさん（32 歳，女性）は，私が勤務する精神科病院に 18 歳から統合失調症で入院していた。私が担当になったのはＦさんが 22 歳の春だった。入院中のＦさんは年配者と過ごすことが多かったため，ロールモデルにできる人がおらず自分の将来像を描けないでいた。そのため，同世代である私は会うたびに話しかけ，Ｆさんの将来について語ってもらった。このことに刺激を受けたＦさんは，次第に自分自身の存在を認め，退院を考えるようになった。<br><br>（問題 34）<br><br>Ｆさんが退院したのは 28 歳の時だった。Ｆさんは受診時には必ず相談室に顔を見せ，これからの夢を語っていった。私はＦさんとの関わりを通し，信頼関係の構築を実感できるようになった。この頃Ｆさんは，経済的自立をするために働きたいと話していた。私は夢の実現への第一歩として，障害者就業・生活支援センターを紹介し，同行訪問することにした。面接の際Ｆさんは，「仕事がしたい」と伝えることはできたが，具体的な業種などの説明ができなかった。<br><br>Ｆさんは希望する業種の説明ができず落ち込んでいたが，普段は説明できていることや，夢や希望を持ち頑張れていることを伝えた。そして，働きたいという意欲を持っていることはＦさんの強みであり，それが自己実現につながることをＦさんに説明した。<br><br>次のうち，この時期のＦさんと「私」の関係について，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 アドボカシー<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ヘルパー・セラピー原則<br><br><input type="checkbox" name="checks" value="3" class="checks">3 パターナリズム<br><br><input type="checkbox" name="checks" value="4" class="checks">4 パートナーシップ<br><br><input type="checkbox" name="checks" value="5" class="checks">5 コンフリクト',
		'answer':'4',
	},
	{
		'id':35,
		'title':'スーパービジョンに向け，自分の関わりを振り返った精神保健福祉士（34 歳，女性）の記録（事例）を読んで，問題 35 について答えなさい。<br><br>〔事　例〕<br><br>Ｆさん（32 歳，女性）は，私が勤務する精神科病院に 18 歳から統合失調症で入院していた。私が担当になったのはＦさんが 22 歳の春だった。入院中のＦさんは年配者と過ごすことが多かったため，ロールモデルにできる人がおらず自分の将来像を描けないでいた。そのため，同世代である私は会うたびに話しかけ，Ｆさんの将来について語ってもらった。このことに刺激を受けたＦさんは，次第に自分自身の存在を認め，退院を考えるようになった。<br><br>Ｆさんが退院したのは 28 歳の時だった。Ｆさんは受診時には必ず相談室に顔を見せ，これからの夢を語っていった。私はＦさんとの関わりを通し，信頼関係の構築を実感できるようになった。この頃Ｆさんは，経済的自立をするために働きたいと話していた。私は夢の実現への第一歩として，障害者就業・生活支援センターを紹介し，同行訪問することにした。面接の際Ｆさんは，「仕事がしたい」と伝えることはできたが，具体的な業種などの説明ができなかった。<br><br>Ｆさんは希望する業種の説明ができず落ち込んでいたが，普段は説明できていることや，夢や希望を持ち頑張れていることを伝えた。そして，働きたいという意欲を持っていることはＦさんの強みであり，それが自己実現につながることをＦさんに説明した。<br><br>（問題 35）<br><br>Ｆさんとの出会いから 10 年が過ぎ，私は病院から地域活動支援センターに異動し，Ｆさんと会う機会も減っていた。ある日のこと，Ｆさんから手紙が届いた。そこには，仕事も生活も順調であること。また，「結婚を前提に付き合っている人がいるが，もし子どもができたらどうすればいいか」と悩みが記されていた。その内容は，結婚や子どもができるかもしれないという将来への希望と，病気を抱えながら育てることへの不安，服薬による胎児への影響を心配しているものであると理解できた。<br><br>次のうち，この時点のＦさんの状況として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 スティグマ<br><br><input type="checkbox" name="checks" value="2" class="checks">2 フラストレーション<br><br><input type="checkbox" name="checks" value="3" class="checks">3 スケープゴート<br><br><input type="checkbox" name="checks" value="4" class="checks">4 アパシー<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アンビバレンス',
		'answer':'5',
	},
	{
		'id':36,
		'title':'次のうち，諸外国の精神保健医療福祉領域において資格化されている人材として，正しいものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 ニュージーランドにおける地域支援ワーカー<br><br><input type="checkbox" name="checks" value="2" class="checks">2 韓国における社会工作師<br><br><input type="checkbox" name="checks" value="3" class="checks">3 アメリカにおける認定ソーシャルワーカー<br><br><input type="checkbox" name="checks" value="4" class="checks">4 イギリスにおける認定ピアスペシャリスト<br><br><input type="checkbox" name="checks" value="5" class="checks">5 中国における精神保健専門要員',
		'answer':'1,3',
	},
	{
		'id':37,
		'title':'人口 40 万人のＮ市では，市の自殺対策推進計画に基づいて，市保健所が中心となり自殺対策を推進している。中学生の自殺報道が続いたため，市の中学校関係者や住民より，「自殺の連鎖が起こらないよう，取組を強化してほしい」と，市保健所へ要望が相次いだ。自殺対策の担当であるＧ精神保健福祉相談員は，市自殺対策推進会議で，児童生徒など若年層への予防的取組の強化を提案することとした。<br><br>次の記述のうち，この時点でのＧ精神保健福祉相談員の提案内容として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 教師を対象とした，ゲートキーパーの養成研修を開催する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 自殺の相談は，保健所での来所面接で一括して対応する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 自殺の危険性が高い人の早期発見は，精神保健福祉士の固有の役割であることを広報する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 メディアリテラシー教育とともに，情報モラル教育及び違法・有害情報対策に協力する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 自殺の連鎖を防ぐため，自殺の場所や手段などの詳細を繰り返し伝える。',
		'answer':'1,4',
	},
	{
		'id':38,
		'title':'次のうち，アンソニー（Anthony, W.）らの提唱した精神科リハビリテーションの基本原則に関する記述として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 様々な技法を駆使するよりも，特定の技法を適用する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 障害のレベルに応じて，本人の参加の可否を判断する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 生活能力の向上よりも，症状の軽減を優先する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 熟慮した上で依存を増やすことは，結果的には本人の自立につながる。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 本人の技能開発の積み重ねが，回復の十分条件となる。',
		'answer':'4',
	},
	{
		'id':39,
		'title':'次の記述のうち，精神科デイ・ケアにおけるリワークプログラムとして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 職場復帰してから開始する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 病気の再発防止よりも，作業能力向上を目指す。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 プログラム終了の判断は産業医が行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 グループワークで，職場の人間関係の課題が再現された場合に気付きを促す。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 本人の同意の有無にかかわらず，情報は精神科デイ・ケア内にとどめる。',
		'answer':'4',
	},
	{
		'id':40,
		'title':'次の記述のうち，包括型地域生活支援プログラム（ＡＣＴ）の標準モデルとして，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 軽度の精神障害者で，かつ本人の希望があれば利用できる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ケアの提供は日中を基本とし，夜間や休日は他機関に委ねる。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 担当者が不在の時にも，多職種チームがケアを提供する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 利用開始時に期限を決めて，短期間で支援を終結する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 仲介型のケアマネジメントを基本とする。',
		'answer':'3',
	},
	{
		'id':41,
		'title':'次の記述のうち，精神保健福祉士が行う援助プロセスにおけるアセスメントの説明として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 援助活動の効果を評価する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 利用者の課題の達成状況を振り返る。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 利用者の状況を把握し，社会資源の精査をする。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 具体的な援助内容を立案する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 援助を受ける意思を利用者に確認する。',
		'answer':'3',
	},
	{
		'id':42,
		'title':'Ｈさん（40 歳，男性）は，アルコール依存症の入院治療を終え，現在は定期的な外来通院やセルフヘルプグループへの参加を継続している。病棟でＨさんを担当していたＪ精神保健福祉士は，退院して半年後，Ｈさんの外来の待合室での様子が気になったことから，「お久しぶり」と声をかけ，面接室で話を聴くこととした。Ｈさんは，「参加している自助グループの人間関係で悩んだりすることもあるが，トラブルにならないように何とか関係を保てている。今日は話を聴いてもらえてよかった」と語り，Ｊ精神保健福祉士はセルフヘルプグループの様子やＨさんの気持ちを傾聴した。<br><br>次のうち，Ｈさんの支援過程においてＪ精神保健福祉士が行ったこの面接の位置づけとして，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 プランニング<br><br><input type="checkbox" name="checks" value="2" class="checks">2 モニタリング<br><br><input type="checkbox" name="checks" value="3" class="checks">3 エバリュエーション<br><br><input type="checkbox" name="checks" value="4" class="checks">4 ターミネーション<br><br><input type="checkbox" name="checks" value="5" class="checks">5 フォローアップ',
		'answer':'5',
	},
	{
		'id':43,
		'title':'次の記述のうち，精神保健福祉士がクライエントに対して行う面接技法の直面化の説明として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 話した内容を別の言葉に換えて簡潔に伝え返すこと。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 話した内容の矛盾点を見定めて指摘すること。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 黙っていることの意味をくみとってまとめて話すこと。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 考えや気持ちを単純な質問で引き出すこと。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 否定的な内容を肯定的な意味づけに変えること。',
		'answer':'2',
	},
	{
		'id':44,
		'title':'次の記述のうち，グループワークにおいて精神保健福祉士が行うこととして，適切なものを 1 つ選びなさい',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 グループ内の規範を定めずに，メンバーの自由な活動を推進する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 メンバーの役割を固定して，効率的にプログラムを進行する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 メンバーの体験談を活用して，社会的スキルの獲得を促進する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 メンバー間の葛藤を回避して，グループ活動が円滑に進むようにする。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 終結期では，メンバー間の凝集性を強化する。',
		'answer':'3',
	},
	{
		'id':45,
		'title':'事例を読んで，次の記述のうち，精神保健福祉士が面接場面でＫさんの母親に提案したこととして，適切なものを 2 つ選びなさい。<br><br>〔事　例〕<br><br>Ｋさん（28 歳，男性）は，大学在学中に統合失調症と診断され，卒業後は就職せずに自宅療養が続いていた。半年前から精神科デイケアを利用している。Ｋさんはデイケア担当の精神保健福祉士との面接で，「やっとデイケアに慣れたところなのに，父にも母にも『世間体が悪いので，早く働け』と毎日言われ，まいっている」と話した。精神保健福祉士は，Ｋさんの了解を得て母親と面接することになった。面接で母親は，「Ｋはデイケアに行く以外は寝てばかり。近所の目も気になり，ついイライラして小言を言ってしまう。もう 28 歳にもなるのに仕事もせず，親戚の集まりで肩身が狭い。父親はもうすぐ 60 歳になるし，早く働いてほしい」と畳み掛けるように話していた。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 「病気の経過や治療方針について主治医から改めて説明してもらってはどうでしょうか」<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「世間の人はあまり見ていないので，気にしないようにしてください」<br><br><input type="checkbox" name="checks" value="3" class="checks">3 「心配事を話せる場として家族教室に参加してはどうでしょうか」<br><br><input type="checkbox" name="checks" value="4" class="checks">4 「Ｋさんを毎朝起こし，生活リズムを管理しましょう」<br><br><input type="checkbox" name="checks" value="5" class="checks">5 「Ｋさんにはデイケアをやめて就労移行支援事業所に通所してもらいましょう」',
		'answer':'1,3',
	},
	{
		'id':46,
		'title':'次の記述のうち，コンサルティの説明として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 コンサルタントから監督及び指導を受ける。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 業務上の課題を抱えた個人，集団，組織，地域社会である。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 コンサルタントがクライエントに対して直接的な援助を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 個人の抱えた私的な悩みをコンサルタントに伝え，相談する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 得られた助言の内容は，自ら評価し，採用するかを決める。',
		'answer':'2,5',
	},
	{
		'id':47,
		'title':'事例を読んで，Ｌさんとその母親に対するＭ精神保健福祉士の対応に関する次の記述のうち，適切なものを 2 つ選びなさい。<br><br>〔事　例〕<br><br>Ｌさん（48 歳，男性）は精神科病院に入院して 1 年が経過している。入院して 6 か月の時点で退院調整を始めた矢先に同居の母親が脳伷塞で緊急入院となり，Ｌさんの動揺も相まって退院が遅れていた。父親は 10 年前に亡くなり他に家族はいない。母親は左上下肢に多少の麻痺が残るも 1 か月前に自宅退院し，訪問介護を利用している。Ｌさんは，「自分も早く退院して苦労をかけた母親の面倒を見て恩返しがしたい」と話し，病棟のＭ精神保健福祉士は相談支援専門員と連携してＬさんの退院支援を進めた。退院前の自宅外泊から病棟に戻ってきたＬさんは，切羽詰まった様子で，「昨日の夕食後，母親が皿を片付けようとした時によろけて尻もちをついてしまった。割れた食器が床に飛び散り，自分はパニックになって何もできなかった。同じようなことがまた起きたらどうすればいいのか」とＭ精神保健福祉士に訴えた。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 Ｌさんの不安が解消されるまで入院できることを伝える。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 Ｌさんと昨日の夕食後に起きたことを順序立てて，一緒に振り返る。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 母親の介護医療院の利用を担当の介護支援専門員に検討してもらう。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 Ｌさん，母親，Ｍ精神保健福祉士，介護支援専門員，相談支援専門員による自宅での会合を提案する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 Ｌさんに相談支援専門員同行で生活介護事業所の見学を勧める。',
		'answer':'2,4',
	},
	{
		'id':48,
		'title':'次のうち，ケアマネジメントに関する記述として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 家族や関係者の抱える負担の解決を一義的な目的とする。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 利用契約を結んだ上で，利用同意の説明を丁寧に行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 ケア計画は本人の意向で変更できないことを説明する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 本人の了解を得て，必要に応じてボランティアと情報共有を図る。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 契約後であっても，本人の希望に応じて担当する相談支援専門員を変更できると伝える。',
		'answer':'4,5',
	},
	{
		'id':49,
		'title':'次の事例を読んで，問題 49 について答えなさい。<br><br>〔事　例〕<br><br>精神保健福祉センターの思春期相談担当のＡ精神保健福祉士（以下「Ａ相談員」という。）の下に，Ｂさん（45 歳，女性）が娘Ｃさん（14 歳）のことで相談に来た。Ｂさんの話によると，「Ｃは 3 か月ほど前の中学 2 年に進級した頃から食べなくなり，急激に痩せてきた。食べるように言うと怒って部屋に入ってしまうので，どうしたらいいか分からない」「養護教諭からこちらの思春期相談を勧められ，本人が拒んだので私だけで相談に来た」という。面談を終えた後，Ａ相談員はＢさんに少し待ってもらい，Ｃさん宛てに書いた手紙を渡してもらうように伝えた。<br><br>次の記述のうち，Ａ相談員がＣさんに書いた手紙の内容として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 あなたは摂食障害という病気なので，早めに相談に来てください。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 なぜ食べられないのでしょうか。一緒に考えていきましょう。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 家族のことや学校のことなど，なんでもいいので話に来ませんか。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 あなたのつらさの要因はご家族にあるので，あなたは何も悪くありませんよ。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 あなたを入院させたくないので，まずこちらに相談に来ませんか。',
		'answer':'3',
	},
	{
		'id':50,
		'title':'次の事例を読んで，問題 50 について答えなさい。<br><br>〔事　例〕<br><br>精神保健福祉センターの思春期相談担当のＡ精神保健福祉士（以下「Ａ相談員」という。）の下に，Ｂさん（45 歳，女性）が娘Ｃさん（14 歳）のことで相談に来た。Ｂさんの話によると，「Ｃは 3 か月ほど前の中学 2 年に進級した頃から食べなくなり，急激に痩せてきた。食べるように言うと怒って部屋に入ってしまうので，どうしたらいいか分からない」「養護教諭からこちらの思春期相談を勧められ，本人が拒んだので私だけで相談に来た」という。面談を終えた後，Ａ相談員はＢさんに少し待ってもらい，Ｃさん宛てに書いた手紙を渡してもらうように伝えた。<br><br>（問題 50）<br><br>2 週間後，ＣさんはＡ相談員の下を訪れ，面談するようになった。Ｃさんは面談の中で，「勉強も部活も頑張ってきた。陸上部で良い成績を出すために減量を始めたが，最近は練習についていけない。部活の友達にはどうしても負けたくない」「家で母親に食べろと言われるのがとても嫌でよくけんかになる。でも，仕事で活躍している母親のことは尊敬している」などと話すようになった。<br><br>週に一度の面談を 1 か月ほど重ね，夏休みを迎えた頃，Ｃさんは，「部活の顧問から体調が心配だから休むように言われてしまった」「家で過食や嘔吐を繰り返している」「もうどうしていいか分からない」とＡ相談員に訴えるようになった。その頃には更に痩せて，肥満度マイナス 25 ％まで減少していた。Ａ相談員はＣさんに児童専門の精神科受診を勧めていたところ，ようやく受診に至った。診察後，主治医は，「今の状態が続くと 2 学期の登校は難しいのではないか」とＣさんとＢさんに伝えたが，Ｃさんは学校も部活も休みたくないと希望した。報告を受けたＡ相談員は，ＣさんとＢさんに学校，医療機関との関係者会議を持つことを提案した。<br><br>次の記述のうち，Ａ相談員が提案した関係者会議の目的として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 Ｃさんが食べない原因を共有し，食事と体重管理の体制を構築する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 学校が実施できる合理的な配慮について確認する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 忙しいＢさんに配慮し，今後の方針を医療機関と学校で決めていく。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 Ｃさんの病状と治療計画に関する情報を学校関係者と共有する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 Ｃさんの気持ちをくんで，放課後の部活動への参加を検討する。',
		'answer':'2',
	},
	{
		'id':51,
		'title':'次の事例を読んで，問題 51 について答えなさい。<br><br>〔事　例〕<br><br>精神保健福祉センターの思春期相談担当のＡ精神保健福祉士（以下「Ａ相談員」という。）の下に，Ｂさん（45 歳，女性）が娘Ｃさん（14 歳）のことで相談に来た。Ｂさんの話によると，「Ｃは 3 か月ほど前の中学 2 年に進級した頃から食べなくなり，急激に痩せてきた。食べるように言うと怒って部屋に入ってしまうので，どうしたらいいか分からない」「養護教諭からこちらの思春期相談を勧められ，本人が拒んだので私だけで相談に来た」という。面談を終えた後，Ａ相談員はＢさんに少し待ってもらい，Ｃさん宛てに書いた手紙を渡してもらうように伝えた。<br><br>2 週間後，ＣさんはＡ相談員の下を訪れ，面談するようになった。Ｃさんは面談の中で，「勉強も部活も頑張ってきた。陸上部で良い成績を出すために減量を始めたが，最近は練習についていけない。部活の友達にはどうしても負けたくない」「家で母親に食べろと言われるのがとても嫌でよくけんかになる。でも，仕事で活躍している母親のことは尊敬している」などと話すようになった。<br><br>週に一度の面談を 1 か月ほど重ね，夏休みを迎えた頃，Ｃさんは，「部活の顧問から体調が心配だから休むように言われてしまった」「家で過食や嘔吐を繰り返している」「もうどうしていいか分からない」とＡ相談員に訴えるようになった。その頃には更に痩せて，肥満度マイナス 25 ％まで減少していた。Ａ相談員はＣさんに児童専門の精神科受診を勧めていたところ，ようやく受診に至った。診察後，主治医は，「今の状態が続くと 2 学期の登校は難しいのではないか」とＣさんとＢさんに伝えたが，Ｃさんは学校も部活も休みたくないと希望した。報告を受けたＡ相談員は，ＣさんとＢさんに学校，医療機関との関係者会議を持つことを提案した。<br><br>（問題 51）<br><br>関係者会議の数日後，Ｂさんは一人でＡ相談員の下へ相談に訪れた。Ｂさんは，「Ｃがこのようになったのは私のせいではないか」「このまま仕事を続けていていいものか悩んでいる。しかし，実は責任のある仕事を任されるようになったばかりで，誰にも相談できずにいる」と思い詰めた様子で語った。<br><br>次の記述のうち，ＢさんへのＡ相談員の対応として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 仕事を続けるかどうかは，Ｃさんに決めてもらってはどうかと提案する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 母親としての役割は大きいので，しばらく仕事は控えるよう助言する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 Ｃさんの病気の要因として考えられることを挙げてもらい，改善策を伝える。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 Ｃさんのためにも，責任ある仕事を引き受けて活躍する姿を見せるよう勧める。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 Ｃさんのケアと仕事を両立する方法を検討し，Ｂさんが選択できるよう支援する。',
		'answer':'5',
	},
	{
		'id':52,
		'title':'次の事例を読んで，問題 52 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（62 歳，男性）は，和食店で働いていた 25 歳の時に統合失調症を発症した。入退院を繰り返したが，40 代以降は母親と同居し，通院のみで病状も落ち着いていた。Ｄさんが 55 歳の時に同居の母親が亡くなって，一人暮らしとなったために生活が乱れて妄想がひどくなり，精神科病院に入院となった。その後，Ｄさんは相続した自宅を不本意ながら売却することになった。Ｄさんは，入院後も何度か病状が再燃し，年が経過した。新たに病棟担当になったＥ精神保健福祉士がＤさんと面接すると，Ｄさんは，「自分は長男だから家を守っていくつもりだった。弟に『兄さんのこれからの生活のためにも売却した方がいい』と押し切られた」と感情的に語った。<br><br>（問題 52）次の記述のうち，この時にＥ精神保健福祉士がＤさんに伝えた言葉として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 「長男として悔しいし，やりきれなかったですね」<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「弟さんはＤさんの意向に反して実家を処分し，ひどい人ですね」<br><br><input type="checkbox" name="checks" value="3" class="checks">3 「病棟の中でＤさんの楽しめることを見付けていきましょう」<br><br><input type="checkbox" name="checks" value="4" class="checks">4 「お母様は亡くなる前にＤさんのことを考えてくれればよかったですね」<br><br><input type="checkbox" name="checks" value="5" class="checks">5 「実家はもうないので，諦めましょう」',
		'answer':'1',
	},
	{
		'id':53,
		'title':'次の事例を読んで，問題 53 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（62 歳，男性）は，和食店で働いていた 25 歳の時に統合失調症を発症した。入退院を繰り返したが，40 代以降は母親と同居し，通院のみで病状も落ち着いていた。Ｄさんが 55 歳の時に同居の母親が亡くなって，一人暮らしとなったために生活が乱れて妄想がひどくなり，精神科病院に入院となった。その後，Ｄさんは相続した自宅を不本意ながら売却することになった。Ｄさんは，入院後も何度か病状が再燃し，年が経過した。新たに病棟担当になったＥ精神保健福祉士がＤさんと面接すると，Ｄさんは，「自分は長男だから家を守っていくつもりだった。弟に『兄さんのこれからの生活のためにも売却した方がいい』と押し切られた」と感情的に語った。<br><br>Ｄさんは，Ｅ精神保健福祉士との面接を通して徐々に落ち着きを取り戻し，主治医より退院の話も出るようになった。そして，「一人暮らしをしてみたい」と話し，退院を希望した。入院中の服薬や食事などの管理は看護師が行っていたが，「今はいい状態なので，帰る家さえ決まれば退院できると思う。一人暮らしは初めてだが，料理はできるし，なんとかなる」と話した。Ｅ精神保健福祉士は，本人も参加するカンファレンスで退院に向けた病棟での働きかけを検討した。<br><br>次の記述のうち，カンファレンスで検討したこととして，適切なものを 1つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 病棟の看護師がＤさんの服薬管理を強化する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ピアサポーターにＤさんの一人暮らしに必要な日用品の買物を依頼する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 病棟で間食の量を決めてカロリーを制限する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 病気の理解を深めるための勉強会に参加する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アパート探しのために外出する。',
		'answer':'4',
	},
	{
		'id':54,
		'title':'次の事例を読んで，問題 54 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（62 歳，男性）は，和食店で働いていた 25 歳の時に統合失調症を発症した。入退院を繰り返したが，40 代以降は母親と同居し，通院のみで病状も落ち着いていた。Ｄさんが 55 歳の時に同居の母親が亡くなって，一人暮らしとなったために生活が乱れて妄想がひどくなり，精神科病院に入院となった。その後，Ｄさんは相続した自宅を不本意ながら売却することになった。Ｄさんは，入院後も何度か病状が再燃し，年が経過した。新たに病棟担当になったＥ精神保健福祉士がＤさんと面接すると，Ｄさんは，「自分は長男だから家を守っていくつもりだった。弟に『兄さんのこれからの生活のためにも売却した方がいい』と押し切られた」と感情的に語った。<br><br>Ｄさんは，Ｅ精神保健福祉士との面接を通して徐々に落ち着きを取り戻し，主治医より退院の話も出るようになった。そして，「一人暮らしをしてみたい」と話し，退院を希望した。入院中の服薬や食事などの管理は看護師が行っていたが，「今はいい状態なので，帰る家さえ決まれば退院できると思う。一人暮らしは初めてだが，料理はできるし，なんとかなる」と話した。Ｅ精神保健福祉士は，本人も参加するカンファレンスで退院に向けた病棟での働きかけを検討した。<br><br>（問題 54）<br><br>Ｄさんは，地域移行支援を利用し，グループホームの体験宿泊を繰り返しながら，退院準備を進めた。掃除やごみ出しに苦労していたが，半年後に退院し，ホームヘルパーに掃除や洗濯を手伝ってもらいながら一人暮らしをしている。また，自宅で料理を楽しんだり，地域活動支援センターの料理会に積極的に参加している。 1 年が経過した頃，相談支援事業所のＦ精神保健福祉士は，ホームヘルパーよりＤさんが時々訪問日を間違えると報告を受けた。また，外来で何度も血糖値の高さも指摘された。Ｄさんも，「この前，道に迷ってしまった。コンロの火を消し忘れてしまった。今まではそんなことなかったのに」と言っており，Ｆ精神保健福祉士は本人と相談して，主治医を含む関係者とカンファレンスを開催することにした。<br><br>次の記述のうち，カンファレンスで示された方針として，適切なものを 2つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 糖尿病の専門外来につなげる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ホームヘルパーは，Ｄさんに代わって買物や料理を行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 困ったときの相談先をあらかじめＤさんと確認しておく。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 Ｄさんが道に迷うことが心配なので，外出を控えてもらう。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 地域活動支援センターの料理会は火を扱うので，他のプログラムを勧める。',
		'answer':'1,3',
	},
	{
		'id':55,
		'title':'次の事例を読んで，問題 55 について答えなさい。<br><br>〔事　例〕<br><br>留学生であるＶ大学 1 年生のＧさん（19 歳，男性）は，日本のアニメに興味を持ち，Ｖ大学に入学した。Ｇさんは大学の学生寮に入寮し，アニメ同好会に入部した。友人もでき，同級生のＨさんとも仲良くなり，楽しい大学生活が始まったと実感していた。しかし，夏休みにＨさんと些細なことでけんかして疎遠になり，夏休み明けから大学を休みがちになった。心配した友人のＪさんはＧさんにソーシャル・ネットワーキング・サービス（ＳＮＳ）で連絡をするが，返信がなかった。12月になりＧさんは，ＳＮＳに「みんなに嫌われているから大学に行きたくない」「最近は怖くて外にも出られない」などと書き込んだ。心配したＪさんは，このことを学生課に相談した。その後，学生課より連絡を受けた，学生相談室のＫ精神保健福祉士（キャンパスソーシャルワーカー）は，今後の対応について検討した。<br><br>（問題 55）<br><br>次の記述のうち，この時点でのＫ精神保健福祉士が検討した内容として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 大学全体で考えるために，全教員にＧさんの情報を知らせる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 Ｊさんに心配している内容を確認する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 学生たちに対して，ＳＮＳのルールについての講習会を開く。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 留学生が一人にならないために，支援体制を整える計画を大学へ提案する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 Ｇさんに連絡し，「なぜ，そのようなことをしたのか」と注意する。',
		'answer':'2',
	},
	{
		'id':56,
		'title':'次の事例を読んで，問題 56 について答えなさい。<br><br>〔事　例〕<br><br>留学生であるＶ大学 1 年生のＧさん（19 歳，男性）は，日本のアニメに興味を持ち，Ｖ大学に入学した。Ｇさんは大学の学生寮に入寮し，アニメ同好会に入部した。友人もでき，同級生のＨさんとも仲良くなり，楽しい大学生活が始まったと実感していた。しかし，夏休みにＨさんと些細なことでけんかして疎遠になり，夏休み明けから大学を休みがちになった。心配した友人のＪさんはＧさんにソーシャル・ネットワーキング・サービス（ＳＮＳ）で連絡をするが，返信がなかった。12月になりＧさんは，ＳＮＳに「みんなに嫌われているから大学に行きたくない」「最近は怖くて外にも出られない」などと書き込んだ。心配したＪさんは，このことを学生課に相談した。その後，学生課より連絡を受けた，学生相談室のＫ精神保健福祉士（キャンパスソーシャルワーカー）は，今後の対応について検討した。<br><br>（問題 56）その後，Ｋ精神保健福祉士と定期的に面接を行うことができるようになったＧさんは，元来努力家で真面目な性格なため，「授業を欠席することに罪悪感がある」「もうみんなに嫌われているかもしれない。不安だ。大学に行けない」「最近は夜も眠れず，体がだるい」と話した。Ｋ精神保健福祉士は，Ｇさんのつらさや不安に寄り添いながらＷ精神科クリニックへの受診を勧め，同行した。診察の結果Ｇさんは適応障害と診断され， 3 か月程度の療養が必要と言われた。それを受け，Ｇさんは両親やＫ精神保健福祉士とも相談し，大学を休学し一度帰国して自国で療養することとなった。<br><br>次の記述のうち，この場面でＫ精神保健福祉士がＧさんにかけた言葉として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 「どんなアニメが好きですか」<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「Ｈさんと何があったのですか」<br><br><input type="checkbox" name="checks" value="3" class="checks">3 「これまで受診しなかったのはどうしてですか」<br><br><input type="checkbox" name="checks" value="4" class="checks">4 「家族の中に，精神科受診歴のある人はいますか」<br><br><input type="checkbox" name="checks" value="5" class="checks">5 「休学について，何か不安はありますか」',
		'answer':'5',
	},
	{
		'id':57,
		'title':'次の事例を読んで，問題 57 について答えなさい。<br><br>〔事　例〕<br><br>留学生であるＶ大学 1 年生のＧさん（19 歳，男性）は，日本のアニメに興味を持ち，Ｖ大学に入学した。Ｇさんは大学の学生寮に入寮し，アニメ同好会に入部した。友人もでき，同級生のＨさんとも仲良くなり，楽しい大学生活が始まったと実感していた。しかし，夏休みにＨさんと些細なことでけんかして疎遠になり，夏休み明けから大学を休みがちになった。心配した友人のＪさんはＧさんにソーシャル・ネットワーキング・サービス（ＳＮＳ）で連絡をするが，返信がなかった。12月になりＧさんは，ＳＮＳに「みんなに嫌われているから大学に行きたくない」「最近は怖くて外にも出られない」などと書き込んだ。心配したＪさんは，このことを学生課に相談した。その後，学生課より連絡を受けた，学生相談室のＫ精神保健福祉士（キャンパスソーシャルワーカー）は，今後の対応について検討した。<br><br>その後，Ｋ精神保健福祉士と定期的に面接を行うことができるようになったＧさんは，元来努力家で真面目な性格なため，「授業を欠席することに罪悪感がある」「もうみんなに嫌われているかもしれない。不安だ。大学に行けない」「最近は夜も眠れず，体がだるい」と話した。Ｋ精神保健福祉士は，Ｇさんのつらさや不安に寄り添いながらＷ精神科クリニックへの受診を勧め，同行した。診察の結果Ｇさんは適応障害と診断され， 3 か月程度の療養が必要と言われた。それを受け，Ｇさんは両親やＫ精神保健福祉士とも相談し，大学を休学し一度帰国して自国で療養することとなった。<br><br>（問題 57）<br><br>3 か月が過ぎた頃，ＧさんからＫ精神保健福祉士に，「元気になったから，また後期から大学に行きたい。来週，日本に戻るので相談したい」と連絡があった。その後の面談では，「友人とうまくやっていけるか心配だし，不安になるとまた眠れなくなる」とＧさんが語った。それを踏まえて，Ｋ精神保健福祉士はＧさんがら復学するための準備として，友人との関係を回復するために，大学の学生相談室で行われているＳＳＴのうち，個別支援ができる「ひとりＳＳＴ」にＧさんを誘ってみた。<br><br>学生相談室で行われた「ひとりＳＳＴ」の場面で，Ｋ精神保健福祉士がＧさんに対して期待したこととして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 自分自身を振り返り，不安になった理由を考えること<br><br><input type="checkbox" name="checks" value="2" class="checks">2 アルバイトを探して，経済的に安定すること<br><br><input type="checkbox" name="checks" value="3" class="checks">3 交際相手を見付けて，楽しい生活を送ること<br><br><input type="checkbox" name="checks" value="4" class="checks">4 ピアサポーターとなって，他の留学生の支援を行うこと<br><br><input type="checkbox" name="checks" value="5" class="checks">5 受診や服薬を忘れずに行い，規則正しい生活を送ること',
		'answer':'1',
	},
	{
		'id':58,
		'title':'次の事例を読んで，問題 58 について答えなさい。<br><br>〔事　例〕<br><br>政令指定都市のＰ市保健所で働くＬ精神保健福祉相談員（精神保健福祉士）（以下「Ｌ相談員」という。）に，Ｐ市に住む父親のＭさん（80 歳）と長女のＡさん（50 歳）の事で，民生委員から相談があった。「ごみが庭にあふれ悪臭もあり，近隣住民が不安に思っている。Ｍさんは外に向かって怒鳴るし，Ａさんの姿を見なくなった。精神的な病気があるかもしれないので保健所に相談に来た。ＭさんとＡさんが心配だ」とのことだった。次の日，Ｌ相談員はＭさん宅を訪問した。<br><br>(問題58)<br><br>次のうち，この時点のＬ相談員が行った援助方法として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 アドミニストレーション<br><br><input type="checkbox" name="checks" value="2" class="checks">2 アサーション・トレーニング<br><br><input type="checkbox" name="checks" value="3" class="checks">3 アウトリーチ<br><br><input type="checkbox" name="checks" value="4" class="checks">4 アクションリサーチ<br><br><input type="checkbox" name="checks" value="5" class="checks">5 アクティング・アウト',
		'answer':'3',
	},
	{
		'id':59,
		'title':'次の事例を読んで，問題 59 について答えなさい。<br><br>〔事　例〕<br><br>政令指定都市のＰ市保健所で働くＬ精神保健福祉相談員（精神保健福祉士）（以下「Ｌ相談員」という。）に，Ｐ市に住む父親のＭさん（80 歳）と長女のＡさん（50 歳）の事で，民生委員から相談があった。「ごみが庭にあふれ悪臭もあり，近隣住民が不安に思っている。Ｍさんは外に向かって怒鳴るし，Ａさんの姿を見なくなった。精神的な病気があるかもしれないので保健所に相談に来た。ＭさんとＡさんが心配だ」とのことだった。次の日，Ｌ相談員はＭさん宅を訪問した。<br><br>（問題59）<br><br>玄関から声をかけるとＭさんは，「俺の勝手だ。ほっといてくれ」と強い口調で言いドアを閉めた。Ａさんの姿は確認できず，名刺を置いてＭさん宅を離れた。Ｌ相談員は，Ｍさん親子についての情報収集や今後の支援方法を，関係機関と検討する必要があると判断し，地域包括支援センターに連絡した。その結果，地域ケア会議が開かれあると判断し，地域包括支援センターに連絡した。その結果，地域ケア会議が開かれ祉協議会の福祉活動専門員，Ｐ市高齢福祉課の担当者，民生委員が参加した。<br><br>次の記述のうち，この時点の会議におけるＬ相談員の提案として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 「積極的な介入をそれぞれ競い合いましょう」<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「期間を設定して，アセスメントをしましょう」<br><br><input type="checkbox" name="checks" value="3" class="checks">3 「所属の専門性をいかした独自の支援計画を立て，それぞれ進めましょう」<br><br><input type="checkbox" name="checks" value="4" class="checks">4 「チームの人数をもっと増やして，支援体制を作りましょう」<br><br><input type="checkbox" name="checks" value="5" class="checks">5「訪問は，どんな状況でも同じメンバーでしましょう」',
		'answer':'2',
	},
	{
		'id':60,
		'title':'次の事例を読んで，問題 60 について答えなさい。<br><br>〔事　例〕<br><br>政令指定都市のＰ市保健所で働くＬ精神保健福祉相談員（精神保健福祉士）（以下「Ｌ相談員」という。）に，Ｐ市に住む父親のＭさん（80 歳）と長女のＡさん（50 歳）の事で，民生委員から相談があった。「ごみが庭にあふれ悪臭もあり，近隣住民が不安に思っている。Ｍさんは外に向かって怒鳴るし，Ａさんの姿を見なくなった。精神的な病気があるかもしれないので保健所に相談に来た。ＭさんとＡさんが心配だ」とのことだった。次の日，Ｌ相談員はＭさん宅を訪問した。<br><br>玄関から声をかけるとＭさんは，「俺の勝手だ。ほっといてくれ」と強い口調で言いドアを閉めた。Ａさんの姿は確認できず，名刺を置いてＭさん宅を離れた。Ｌ相談員は，Ｍさん親子についての情報収集や今後の支援方法を，関係機関と検討する必要があると判断し，地域包括支援センターに連絡した。その結果，地域ケア会議が開かれあると判断し，地域包括支援センターに連絡した。その結果，地域ケア会議が開かれ祉協議会の福祉活動専門員，Ｐ市高齢福祉課の担当者，民生委員が参加した。<br><br>(問題 60）<br><br>Ｌ相談員が訪問を続けると，Ａさんが玄関先に出てくれるようになった。 2 か月が過ぎた頃Ａさんから，「何とかしようと思っていました。でも父は怒りやすくなり，話もかみ合わなくて。私も気分が落ちて，朝は布団から出られなくなって。 2 年前に15 年ほど勤めた会社を辞めたんです。それから，どうしようもなく…」と話があった。詳しく話を聴くと，Ｍさんには認知症，Ａさんには精神疾患の疑いがそれぞれあり，支援を希望していることが分かった。<br><br>チームによる支援を続け 1 年が過ぎた。少しずつ居住環境は改善されつつある。また，現在Ｍさんは通所介護（デイサービス）を利用しており，Ａさんは精神科クリニックへ通院を続けている。Ａさんは，「気持ちが落ち着いてきたような気がします。でもこれからですね」とＬ相談員に話した。この支援をきっかけに，Ｌ相談員はＭさん親子のような課題を持つ方への支援の充実や支援体制の構築が必要と考え，「障害者総合支援法」に基づくＰ市協議会で検討することを提案してきた。<br><br>次の記述のうち，Ｌ相談員がＰ市協議会で最初に提案したコミュニティソーシャルワーク実践の内容として，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 ＳＷＯＴ分析を用いて，住民意識や支援者の状況を把握する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 Ｐ市の全戸訪問を行い，セルフネグレクトの可能性がある世帯を把握する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 Ｍさん家族に対応した支援ネットワークの形を変えず，他の地域課題にも対応していく。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 Ｐ市全域を対象として，見守りボランティアを募る。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 メーリングリストを活用して，クライエントの個人情報を迅速に共有する。',
		'answer':'1',
	},
	{
		'id':61,
		'title':'措置入院に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 精神保健指定医の権限で入院を決定する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「精神保健福祉法」により，国等の設置した精神科病院又は指定病院に入院させることができる。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 病院の管理者は，本人へ入院に関する告知を行う義務がある。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 定期病状報告は市町村長に対して行う。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 病院の管理者が措置の解除を行う。',
		'answer':'2',
	},
	{
		'id':62,
		'title':'「医療観察法」に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 精神保健審判員は生活環境調査を実施する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 検察官からの申立てを受けた家庭裁判所は合議体を形成する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 通院医療の継続が必要な場合は，保護観察所の長が延長の申立てを行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 地方裁判所は処遇の実施計画を作成する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 入院処遇における退院の決定は，保護観察所が行う。',
		'answer':'3',
	},
	{
		'id':63,
		'title':'発達障害者支援センターに関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 子ども・若者育成支援推進法に規定された機関である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 発達障害についての研修を行う。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 特別支援教育コーディネーターの配置が義務づけられている。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 設置主体は市町村である。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 利用には障害支援区分の認定を受ける必要がある。',
		'answer':'2',
	},
	{
		'id':64,
		'title':'精神障害者への経済的な支援に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 初診日が 20 歳未満である精神障害者は，特別障害給付金が支給される。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 雇用保険における求職者給付の基本手当の申請窓口は，労働基準監督署である。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 精神障害者は，特別障害者手当の支給対象より除外される。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 生活困窮者住居確保給付金は，賃貸住宅の入居契約のための敷金，礼金を基準として支給される。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 精神障害者保健福祉手帳所持者のうち，障害等級 2 級の者は所得税の障害者控除の対象である。',
		'answer':'5',
	},
	{
		'id':65,
		'title':'次のうち，保健所の精神保健福祉業務として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 精神障害者保健福祉手帳の交付決定<br><br><input type="checkbox" name="checks" value="2" class="checks">2 日常生活自立支援事業の事務<br><br><input type="checkbox" name="checks" value="3" class="checks">3 医療保護入院者の入院届の受理<br><br><input type="checkbox" name="checks" value="4" class="checks">4 障害支援区分の認定調査の実施<br><br><input type="checkbox" name="checks" value="5" class="checks">5 地方精神保健福祉審議会の設置',
		'answer':'3',
	},
	{
		'id':66,
		'title':'アルコホーリクス・アノニマス（ＡＡ）に関する次の記述のうち，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 アルコール依存症者の家族を対象としたグループである。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 アルコール依存症者の就労支援を目的としたプログラムである。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 組織の運営は専門職の関与を前提とする。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 12 のステップを採用している。<br><<input type="checkbox" name="checks" value="5" class="checks">br>5 実名での参加を原則とする。',
		'answer':'4',
	},
	{
		'id':67,
		'title':'更生保護制度に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 矯正施設での施設内処遇が原則となる。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 仮釈放の決定を行うのは，地方裁判所である。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 保護観察の期間は，保護観察所が決定する。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 仮釈放者は，自立更生促進センターに入所することができる。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 地域生活定着支援センターは，保護観察所に併設される。',
		'answer':'4',
	},
	{
		'id':68,
		'title':'退院後生活環境相談員に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 担当できる医療保護入院者の人数の目安は概ね 50 人以下である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 措置入院者の退院促進も対象となる。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 精神療養病棟に必置としている。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 「精神保健福祉法」第 27 条第 3 <input type="checkbox" name="checks" value="5" class="checks">項に基づく精神保健指定医の診察に立ち会う。<br><br>5 精神保健福祉士として 3 年以上の相談・指導経験を必要とする。',
		'answer':'1',
	},
	{
		'id':69,
		'title':'Ｑ市では，精神障害者の就労への意向の実態と関連要因を把握するため，市内の就労移行支援事業所の全利用者を対象に郵送によるアンケートを行った。調査票は主に尺度で構成された。さらに，同意が得られた者には調査員が自宅に訪問し，就労に対する気持ちの変化を聴き取る面接調査を行った。アンケートの分析から，当事者同士の交流頻度と就労への意欲との間に正の相関関係があることが分かった。また面接の語りの分析からは，仲間の就労体験を聞くことで自分自身も就労したいという意欲につながる過程が示された。<br><br>次のうち，この調査で用いられた社会調査の手法として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 層化抽出法<br><br><input type="checkbox" name="checks" value="2" class="checks">2 ミックス法<br><br><input type="checkbox" name="checks" value="3" class="checks">3 参与観察法<br><br><input type="checkbox" name="checks" value="4" class="checks">4 コホート調査法<br><br><input type="checkbox" name="checks" value="5" class="checks">5 パネル調査法',
		'answer':'2',
	},
	{
		'id':70,
		'title':'次の事例を読んで，問題 70 について答えなさい。<br><br>〔事　例〕<br><br>Ｂさん（50 歳，男性）は 30 代の頃に統合失調症を発症し，両親が自宅で面倒を見ていた。しかし，その両親が交通事故で亡くなると，病状が極めて不安定になり，最終的にＸ病院に 2010 年（平成 22 年）に入院した。入院後 1 年で病状は落ち着いたものの，退院が迫ると病状が悪化するなど，不安定な状態になることを 10 年ほど繰り返していた。<br><br>地域の相談支援事業所のＣ精神保健福祉士は，Ｘ病院からＢさんについて紹介を受け，Ｂさんに話を聞いた。Ｂさんは，「退院はともかく，外の世界が今どうなっているかは知りたい。あと病院の外で食事をしてみたい」とぽつぽつと話した。Ｂさんは，「障害者総合支援法」における地域相談支援に基づくサービスを利用し，Ｃ精神保健福祉士と一緒に社会資源の見学をし，外出のついでに食事などをした。外出のたびにＣ精神保健福祉士は，Ｂさんに地域での暮らしをイメージしてもらえるように働きかけた。<br><br>次のうち，Ｂさんがこの時点で利用した制度の名称として，正しいものを1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 行動援護<br><br><input type="checkbox" name="checks" value="2" class="checks">2 同行援護<br><br><input type="checkbox" name="checks" value="3" class="checks">3 機能訓練<br><br><input type="checkbox" name="checks" value="4" class="checks">4 地域移行支援<br><br><input type="checkbox" name="checks" value="5" class="checks">5 成年後見制度利用支援事業',
		'answer':'4',
	},
	{
		'id':71,
		'title':'次の事例を読んで，問題 71 について答えなさい。<br><br>〔事　例〕<br><br>Ｂさん（50 歳，男性）は 30 代の頃に統合失調症を発症し，両親が自宅で面倒を見ていた。しかし，その両親が交通事故で亡くなると，病状が極めて不安定になり，最終的にＸ病院に 2010 年（平成 22 年）に入院した。入院後 1 年で病状は落ち着いたものの，退院が迫ると病状が悪化するなど，不安定な状態になることを 10 年ほど繰り返していた。<br><br>地域の相談支援事業所のＣ精神保健福祉士は，Ｘ病院からＢさんについて紹介を受け，Ｂさんに話を聞いた。Ｂさんは，「退院はともかく，外の世界が今どうなっているかは知りたい。あと病院の外で食事をしてみたい」とぽつぽつと話した。Ｂさんは，「障害者総合支援法」における地域相談支援に基づくサービスを利用し，Ｃ精神保健福祉士と一緒に社会資源の見学をし，外出のついでに食事などをした。外出のたびにＣ精神保健福祉士は，Ｂさんに地域での暮らしをイメージしてもらえるように働きかけた。<br><br>（問題 71）<br><br>ＢさんはＣ精神保健福祉士と一緒に行動するにつれ，退院に興味を持ち始めたが，「身寄りのない自分は困ったときに誰にも相談できない。心細い」と不安を訴えた。Ｃ精神保健福祉士は，「障害者総合支援法」における地域相談支援に基づくサービスを紹介し，随時，退院後の相談に乗ることとした。<br><br>次の記述のうち，Ｂさんが利用した制度の説明として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 利用期間は原則無期限である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 障害支援区分の区分 3 以上の者が対象である。<br><input type="checkbox" name="checks" value="3" class="checks"><br>3 家族との同居から一人暮らしに移行した者も対象である。<br<input type="checkbox" name="checks" value="4" class="checks">><br>4 宿泊型自立訓練の利用者は対象である。<br<input type="checkbox" name="checks" value="5" class="checks">><br>5 共同生活援助（グループホーム）の利用者は対象である。',
		'answer':'3',
	},
	{
		'id':72,
		'title':'次の事例を読んで，問題 72 について答えなさい。<br><br>〔事　例〕<br><br>Ｂさん（50 歳，男性）は 30 代の頃に統合失調症を発症し，両親が自宅で面倒を見ていた。しかし，その両親が交通事故で亡くなると，病状が極めて不安定になり，最終的にＸ病院に 2010 年（平成 22 年）に入院した。入院後 1 年で病状は落ち着いたものの，退院が迫ると病状が悪化するなど，不安定な状態になることを 10 年ほど繰り返していた。<br><br>地域の相談支援事業所のＣ精神保健福祉士は，Ｘ病院からＢさんについて紹介を受け，Ｂさんに話を聞いた。Ｂさんは，「退院はともかく，外の世界が今どうなっているかは知りたい。あと病院の外で食事をしてみたい」とぽつぽつと話した。Ｂさんは，「障害者総合支援法」における地域相談支援に基づくサービスを利用し，Ｃ精神保健福祉士と一緒に社会資源の見学をし，外出のついでに食事などをした。外出のたびにＣ精神保健福祉士は，Ｂさんに地域での暮らしをイメージしてもらえるように働きかけた。<br><br>ＢさんはＣ精神保健福祉士と一緒に行動するにつれ，退院に興味を持ち始めたが，「身寄りのない自分は困ったときに誰にも相談できない。心細い」と不安を訴えた。Ｃ精神保健福祉士は，「障害者総合支援法」における地域相談支援に基づくサービスを紹介し，随時，退院後の相談に乗ることとした。<br><br>（問題 72）<br><br>退院したＢさんは，両親から残された自宅で，上記の支援とホームヘルプサービスを利用して当初生活していた。しかし実際に一人暮らしをしてみると生活上の困難が思いの外大きいことが明らかになり，共同生活援助（グループホーム）を利用することになった。一旦はグループホームに馴染んだかに見えたＢさんだったが，そのうちＣ精神保健福祉士に，「人と一緒に暮らすのは自分にはどうしても向いていない」「にぎやかな感じが苦手」という訴えを漏らすようになった。そこでＣ精神保健福祉士は，Ｂさんと相談しながら改めて自宅での生活を検討した。その中で，ある法律の改正で2018 年（平成 30 年）に新設された，居宅における自立した生活を営む上での支援を目的とし，原則 1 年の期限で訪問と適宜の相談を提供するサービスを利用することとした。<br><br>次のうち，このサービスを利用する際に必要な手続として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 日常生活自立支援事業の利用<br><br><input type="checkbox" name="checks" value="2" class="checks">2 障害支援区分の認定<br><br><input type="checkbox" name="checks" value="3" class="checks">3 自立支援医療（精神通院医療）の受給<br><br><input type="checkbox" name="checks" value="4" class="checks">4 サービス等利用計画の作成<br><br><input type="checkbox" name="checks" value="5" class="checks">5 指定通院医療機関への通院',
		'answer':'4',
	},
	{
		'id':73,
		'title':'「障害者総合支援法」に基づく宿泊型自立訓練に関する次の記述のうち，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 標準利用期間は原則 1 年である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 市町村地域生活支援事業の任意事業に位置づけられている。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 介護給付費が支給される事業である。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 介護サービス包括型や外部サービス型などの種別がある。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 所得に応じた利用者負担上限月額が設けられている。',
		'answer':'5',
	},
	{
		'id':74,
		'title':'次の記述のうち，「障害者雇用促進法」に基づく職場適応援助者（ジョブコーチ）に関する説明として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 職業リハビリテーションに関して研究する。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 円滑な就職と職場適応ができるよう，障害者と事業所の双方を支援する。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 就業面の支援に併せて，体調や生活のリズムの管理に関する支援を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 対象となる障害者が，正式に就職してから支援を開始する。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 障害者雇用率未達成の事業主に対して指導する。',
		'answer':'2,3',
	},
	{
		'id':75,
		'title':'次の記述のうち，厚生労働省が発表した障害者の雇用の状況等について，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 「平成 30 年度障害者の職業紹介状況等」によれば，2018 年度（平成 30 年度）のハローワークを通じた障害者の就職率は 20 ％未満である。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「平成 30 年度障害者の職業紹介状況等」によれば，2018 年度（平成 3<input type="checkbox" name="checks" value="3" class="checks">0 年度）の障害者雇用の就職件数において精神障害者の割合は 30 ％未満である。<br<input type="checkbox" name="checks" value="4" class="checks">><br>3 「令和元年障害者雇用状況の集計結果」によれば，民間企業における実雇用率は企業の規模が大きいほど高い。<br<input type="checkbox" name="checks" value="5" class="checks">><br>4 「令和元年障害者雇用状況の集計結果」によれば，民間企業において雇用されている精神障害者の数は，ここ 5 年間で横ばいである。<br><br>5 「令和元年障害者雇用状況の集計結果」によれば，民間企業において雇用されている障害者の数では，精神障害者が知的障害者よりも多い。',
		'answer':'3',
	},
	{
		'id':76,
		'title':'次のうち，精神障害者の場合，精神障害者保健福祉手帳の所持が前提となるものとして，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 就労移行支援事業所の利用<br><br><input type="checkbox" name="checks" value="2" class="checks">2 「障害者雇用促進法」に基づく障害者雇用率の算定<br><br><input type="checkbox" name="checks" value="3" class="checks">3 救護施設への入所<br><br><input type="checkbox" name="checks" value="4" class="checks">4 住宅入居等支援事業の利用<br><br><input type="checkbox" name="checks" value="5" class="checks">5 自立準備ホームへの入所',
		'answer':'2',
	},
	{
		'id':77,
		'title':'次の記述のうち，「障害者総合支援法」における基幹相談支援センターの説明として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 障害者への医学的，心理学的及び職能的判定業務を行う。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 自立支援給付に位置づけられる。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 職業準備講習を行う。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 発達障害者は支援の対象外である。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 地域の相談支援体制の強化に取り組む。',
		'answer':'5',
	},
	{
		'id':78,
		'title':'次の事例を読んで，問題 78 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（70 歳，女性）は，統合失調症で精神科病院に長期入院をしていたが，10 年前に退院に向けた支援を受けながら地域に戻った。その後，定期的な通院を続け，「障害者総合支援法」に基づくＹ機関に通所しながらアパートで一人暮らしを続けている。Ｄさんには妹がおり，アパートの近くに住んでいて関係は良好である。Ｄさんは週 3 回通所しているＹ機関で，公園の清掃活動とお菓子の箱折等の作業を行い，月 1万円程度の工賃を得ている。ＤさんはＹ機関と雇用契約を結んでいない。<br><br>（問題 78）<br><br>次のうち，Ｄさんが現在利用しているＹ機関として，正しいものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 就労継続支援Ｂ型事業所<br><br><input type="checkbox" name="checks" value="2" class="checks">2 就労継続支援Ａ型事業所<br><br><input type="checkbox" name="checks" value="3" class="checks">3 就労移行支援事業所<br><br><input type="checkbox" name="checks" value="4" class="checks">4 地域障害者職業センター<br><br><input type="checkbox" name="checks" value="5" class="checks">5 障害者就業・生活支援センター',
		'answer':'1',
	},
	{
		'id':79,
		'title':'次の事例を読んで，問題 79 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（70 歳，女性）は，統合失調症で精神科病院に長期入院をしていたが，10 年前に退院に向けた支援を受けながら地域に戻った。その後，定期的な通院を続け，「障害者総合支援法」に基づくＹ機関に通所しながらアパートで一人暮らしを続けている。Ｄさんには妹がおり，アパートの近くに住んでいて関係は良好である。Ｄさんは週 3 回通所しているＹ機関で，公園の清掃活動とお菓子の箱折等の作業を行い，月 1万円程度の工賃を得ている。ＤさんはＹ機関と雇用契約を結んでいない。<br><br>（問題 79）<br><br>Ｄさんは，Ｙ機関での工賃と障害年金を受給しながら生計を立てている。Ｄさんは安定した地域生活を送っていたが，最近になって日常の複雑な動作が難しくなり，運動能力の低下も顕著になってきた。Ｄさん自身もそのことを自覚し，Ｙ機関のＥ職員（精神保健福祉士）に，健康面での不安を抱いていること，日常生活においても調理や家事も少しずつ大変になってきていることの相談をした。そこでＥ職員はＺ相談支援事業所のＦ職員（精神保健福祉士）に担当者会議の開催を依頼した。Ｙ機関ではＤさんの作業内容の見直しを検討した。その結果，公園の清掃活動を中止し軽作業のみ行うこととなり，通所回数を週 2 回にすることにした。Ｅ職員は「障害者総合支援法」に基づき個別支援計画の変更を行った。<br><br>次の記述のうち，Ｅ職員が行った個別支援計画の変更に関する説明として，適切なものを 2 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 変更後，12 か月に 1 回モニタリングをしなければならない。<br><br><input type="checkbox" name="checks" value="2" class="checks">2 変更にはＤさんの妹の同意が必須である。<br><br><input type="checkbox" name="checks" value="3" class="checks">3 変更に当たっては，障害者職業カウンセラーが最終的な責任を持つ。<br><br><input type="checkbox" name="checks" value="4" class="checks">4 変更後の個別支援計画を，Ｄさんに交付しなければならない。<br><br><input type="checkbox" name="checks" value="5" class="checks">5 変更に当たっては，Ｅ職員はＤさんと面接を行う。',
		'answer':'4,5',
	},
	{
		'id':80,
		'title':'次の事例を読んで，問題 80 について答えなさい。<br><br>〔事　例〕<br><br>Ｄさん（70 歳，女性）は，統合失調症で精神科病院に長期入院をしていたが，10 年前に退院に向けた支援を受けながら地域に戻った。その後，定期的な通院を続け，「障害者総合支援法」に基づくＹ機関に通所しながらアパートで一人暮らしを続けている。Ｄさんには妹がおり，アパートの近くに住んでいて関係は良好である。Ｄさんは週 3 回通所しているＹ機関で，公園の清掃活動とお菓子の箱折等の作業を行い，月 1万円程度の工賃を得ている。ＤさんはＹ機関と雇用契約を結んでいない。<br><br>Ｄさんは，Ｙ機関での工賃と障害年金を受給しながら生計を立てている。Ｄさんは安定した地域生活を送っていたが，最近になって日常の複雑な動作が難しくなり，運動能力の低下も顕著になってきた。Ｄさん自身もそのことを自覚し，Ｙ機関のＥ職員（精神保健福祉士）に，健康面での不安を抱いていること，日常生活においても調理や家事も少しずつ大変になってきていることの相談をした。そこでＥ職員はＺ相談支援事業所のＦ職員（精神保健福祉士）に担当者会議の開催を依頼した。Ｙ機関ではＤさんの作業内容の見直しを検討した。その結果，公園の清掃活動を中止し軽作業のみ行うこととなり，通所回数を週 2 回にすることにした。Ｅ職員は「障害者総合支援法」に基づき個別支援計画の変更を行った。<br><br>（問題 80）<br><br>Ｆ職員はＤさんと面接を行い，Ｄさんの生活状況を確認した。元々Ｄさんは整理整頓ができていたが最近では体が思うように動かず，ごみ出しができなくなっていたことや，一人で調理をすることが難しくなっていたことが分かった。また，日常生活のサポートは妹に頼っていたことも分かった。Ｆ職員が介護保険サービスの利用を提案したところ，Ｄさんも妹も利用に前向きな回答をした。そこで，Ｆ職員はＤさんの介護保険サービスの利用に向けて調整を行った。その後，Ｄさんは介護保険サービスの利用申請を行い，認定調査の結果，要介護 1 の判定が出た。<br><br>次のうち，Ｆ職員がＤさんに提案した介護保険サービスとして，適切なものを 1 つ選びなさい。',
		'text':'<input type="checkbox" name="checks" value="1" class="checks">1 重度訪問介護<br><br><input type="checkbox" name="checks" value="2" class="checks">2 訪問介護<br><br><input type="checkbox" name="checks" value="3" class="checks">3 訪問入浴介護<br><br><input type="checkbox" name="checks" value="4" class="checks">4 居宅介護<br><br><input type="checkbox" name="checks" value="5" class="checks">5 療養介護',
		'answer':'2',
	}
];